//! On-chain writes against the Poa TaskManager contract.
// The TaskManager ABI methods generated by `sol!` mirror the on-chain function
// signatures (createTask has 9 params), which trips clippy's argument-count lint
// on generated code we don't control.
#![allow(clippy::too_many_arguments)]

use crate::client::{PoaClient, PoaError};
use alloy::primitives::aliases::U48;
use alloy::primitives::{Address, Bytes, B256, U256};
use alloy::sol;
use tracing::info;

sol! {
    #[sol(rpc)]
    interface ITaskManager {
        function createTask(
            uint256 payout,
            bytes title,
            bytes32 metadataHash,
            bytes32 pid,
            address bountyToken,
            uint256 bountyPayout,
            bool requiresApplication,
            uint48 absoluteDeadline,
            uint32 completionWindow
        ) external;

        function updateTask(
            uint256 id,
            uint256 newPayout,
            bytes newTitle,
            bytes32 newMetadataHash,
            address newBountyToken,
            uint256 newBountyPayout,
            uint48 newAbsoluteDeadline,
            uint32 newCompletionWindow
        ) external;

        function assignTask(uint256 id, address assignee) external;
        function completeTask(uint256 id) external;
        function rejectTask(uint256 id, bytes32 rejectionHash) external;
        function cancelTask(uint256 id) external;
    }
}

/// Outcome of a submitted transaction.
#[derive(Debug, Clone)]
pub struct TxOutcome {
    /// Transaction hash (0x-prefixed).
    pub hash: String,
    /// Whether the transaction succeeded.
    pub success: bool,
    /// Block the transaction was mined in, if known.
    pub block: Option<u64>,
}

impl TxOutcome {
    fn from_receipt(receipt: alloy::rpc::types::TransactionReceipt) -> Self {
        Self {
            hash: format!("{:?}", receipt.transaction_hash),
            success: receipt.status(),
            block: receipt.block_number,
        }
    }
}

/// Parameters for creating a task (bounties intentionally unsupported for now).
pub(crate) struct CreateTaskParams {
    pub payout: U256,
    pub title: String,
    pub metadata_hash: B256,
    pub project_id: B256,
    pub requires_application: bool,
    pub absolute_deadline: u64,
    pub completion_window: u32,
}

/// Parameters for a full task update.
pub(crate) struct UpdateTaskParams {
    pub task_id: U256,
    pub payout: U256,
    pub title: String,
    pub metadata_hash: B256,
    pub bounty_token: Address,
    pub bounty_payout: U256,
    pub absolute_deadline: u64,
    pub completion_window: u32,
}

macro_rules! send_tx {
    ($self:expr, $label:expr, $call:expr) => {{
        let receipt = $call
            .send()
            .await
            .map_err(|e| PoaError::Chain(format!(concat!($label, " failed to send: {}"), e)))?
            .get_receipt()
            .await
            .map_err(|e| PoaError::Chain(format!(concat!($label, " receipt error: {}"), e)))?;
        let outcome = TxOutcome::from_receipt(receipt);
        info!(tx = %outcome.hash, success = outcome.success, concat!("Poa ", $label, " transaction mined"));
        if !outcome.success {
            return Err(PoaError::Chain(format!(
                concat!($label, " transaction reverted: {}"),
                outcome.hash
            )));
        }
        Ok(outcome)
    }};
}

impl PoaClient {
    fn task_manager(
        &self,
    ) -> ITaskManager::ITaskManagerInstance<impl alloy::providers::Provider + Clone> {
        ITaskManager::new(self.config.task_manager, self.provider())
    }

    pub(crate) async fn create_task(&self, p: CreateTaskParams) -> Result<TxOutcome, PoaError> {
        let tm = self.task_manager();
        send_tx!(
            self,
            "createTask",
            tm.createTask(
                p.payout,
                Bytes::from(p.title.into_bytes()),
                p.metadata_hash,
                p.project_id,
                Address::ZERO,
                U256::ZERO,
                p.requires_application,
                U48::from(p.absolute_deadline),
                p.completion_window,
            )
        )
    }

    pub(crate) async fn update_task(&self, p: UpdateTaskParams) -> Result<TxOutcome, PoaError> {
        let tm = self.task_manager();
        send_tx!(
            self,
            "updateTask",
            tm.updateTask(
                p.task_id,
                p.payout,
                Bytes::from(p.title.into_bytes()),
                p.metadata_hash,
                p.bounty_token,
                p.bounty_payout,
                U48::from(p.absolute_deadline),
                p.completion_window,
            )
        )
    }

    pub(crate) async fn assign_task(
        &self,
        task_id: U256,
        assignee: Address,
    ) -> Result<TxOutcome, PoaError> {
        let tm = self.task_manager();
        send_tx!(self, "assignTask", tm.assignTask(task_id, assignee))
    }

    pub(crate) async fn complete_task(&self, task_id: U256) -> Result<TxOutcome, PoaError> {
        let tm = self.task_manager();
        send_tx!(self, "completeTask", tm.completeTask(task_id))
    }

    pub(crate) async fn reject_task(
        &self,
        task_id: U256,
        rejection_hash: B256,
    ) -> Result<TxOutcome, PoaError> {
        let tm = self.task_manager();
        send_tx!(self, "rejectTask", tm.rejectTask(task_id, rejection_hash))
    }

    pub(crate) async fn cancel_task(&self, task_id: U256) -> Result<TxOutcome, PoaError> {
        let tm = self.task_manager();
        send_tx!(self, "cancelTask", tm.cancelTask(task_id))
    }
}
